# Site config
baseurl: "/virtual-fort-snelling-documentation"

# User config
title: "Virtual Fort Snelling Documentation"
author: "AISOS"
description: "Virtual Fort Snelling Documentation"
email: "aisos@umn.edu"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'highlight'

# User collections.
collections:
    pages:
        output: true

# Collection defaults.
defaults:
-
    scope:
        path: "_posts"
        type: "posts"
    values:
        layout: page
-
    scope:
        path: "_pages"
        type: "pages"
    values:
        layout: page